apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xy6v2q04b-java-quarkus
  janus-idp.io/tekton: xy6v2q04b-java-quarkus
  backstage.io/kubernetes-id: xy6v2q04b-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xy6v2q04b-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
